# pyproject.toml

[build-system]
requires = ["setuptools>=64.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "illegal_character_check"
version = "0.0.1"
description = "A script to find and report on all illegal characters in a filesystem."
readme = "README.md"
authors = [{ name = "Steven Cucolo", email = "steven.cucolo@natgeo.com" }]

[project.scripts]
icc = "illegal_character_check.__main__:main"