# pyproject.toml

[build-system]
requires = ["setuptools>=64.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "charchecker"
version = "0.0.1"
description = "A script to find and report on all illegal characters in a filesystem."
readme = "README.md"
authors = [{ name = "Steven Cucolo", email = "steven.cucolo@natgeo.com" }]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
requires-python = ">=3.7"
dependencies = [
  "pyyaml=*",
]

[project.scripts]
icc = "illegal_character_check.__main__:main"

[project.urls]
"Homepage" = "https://github.com/scuc/Illegal-Character-Check"